# Generated by Django 3.1.5 on 2021-01-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_livro', models.CharField(max_length=20)),
                ('autor_livro', models.CharField(max_length=20)),
                ('editora_livro', models.CharField(max_length=20)),
                ('valor_livro', models.CharField(max_length=5)),
            ],
        ),
    ]
