# Generated by Django 3.1.5 on 2021-01-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_livros', '0004_auto_20210122_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='valor_livro',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
