# Generated by Django 3.1.5 on 2021-01-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_livros', '0005_auto_20210122_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='valor_livro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
